module.exports.descriptors = [
    'Gaming',
    'Rogue',
    'Board Game',
    'Tabletop',
    'RPG',
    'Merlins',
    'Sci-Fi',
    'Role Players',
    'Crimson Castle',
    'The Mad Hermit',
    'Tier 1',
    'Imperial',
    'Next Gen',
    'The Vault',
    'Gamesville',
    'Heros',
    'Goliath',
    'Dragons Hoard',
    'Griffins Roost',
    'Crossroad',
    'Eternal',
    'Gauntlet',
    'Mastermind'
]

module.exports.places = [
    'Haven',
    'Gallery',
    'Shoppe',
    'Nexus',
    'Hideout',
    'Cafe',
    'Central',
    'Citadel',
    'Keep',
    'Games',
    'Tryst',
    'Outpost',
    'Cave',
    'Room',
    'Lounge',
    'Brothers',
    'Emporium',
    'Inn',
    'Tower',
    'Kingdom'
]